### ISSUE TITLE
PiGraph-X and POSA-I

### ISSUE THREAD

**Issue by nanfengguli** [zkf1997/COINS#1]
Hi, would you be willing to provide code and data about PiGraph-X and POSA-I? 
Would appreciate it if you could!

**Comment by zkf1997** [comment]
Thanks for your query.  I will release the code for baselines in a recent update together with some code cleaning and documentation. 
Regarding POSA-I, I will release the part of generating body from action labels and refer to the original [POSA](https://github.com/mohamedhassanmus/POSA) repo for the part of placing bodies into scenes.

**Comment by wang-zm18** [comment]
Hello，@zkf1997,  how to get the corresponding train.pkl and test.pkl in PiGraph-X?  When I ran synthesize.py, it always occurs the problem about missing train.pkl file.

**Comment by zkf1997** [comment]
> Hello，@zkf1997, how to get the corresponding train.pkl and test.pkl in PiGraph-X? When I ran synthesize.py, it always occurs the problem about missing train.pkl file.

you can find the data files here: https://drive.google.com/drive/folders/1rze_8M8MysYt8jth3MT4DzPy0dXHvTiN

**Comment by wang-zm18** [comment]
Thanks for your reply! I have tried to set the corresponding path of .pkl files, but when I run the following code 
> python  -W ignore synthesize.py --use_penetration 0 --composition 0 --visualize 1 --gender neutral --num_results 8 --num_skeletons 8 --num_translations 32 --num_rotations 12 --interaction 'sit on-chair' --scene_name 'MPH16' --save_dir pigraph_normal

It occurs this problem:
![image](https://user-images.githubusercontent.com/47704679/200118425-2f8dd75f-038f-45f9-bc0b-af70dd9cab9e.png)

**Comment by zkf1997** [comment]
> Thanks for your reply! I have tried to set the corresponding path of .pkl files, but when I run the following code
> 
> > python  -W ignore synthesize.py --use_penetration 0 --composition 0 --visualize 1 --gender neutral --num_results 8 --num_skeletons 8 --num_translations 32 --num_rotations 12 --interaction 'sit on-chair' --scene_name 'MPH16' --save_dir pigraph_normal
> 
> It occurs this problem: ![image](https://user-images.githubusercontent.com/47704679/200118425-2f8dd75f-038f-45f9-bc0b-af70dd9cab9e.png)

From the error, this is a problem related to the open3d visualization. I would like to suggest checking your platform and open3d documentation. Probably this is because you are running on a headless server that does not have a display.

**Comment by wang-zm18** [comment]
Thank you！ I ran this code on the remote server without displayer.  But I indeed use the `osmesa ` mode. I am not farmilar with open3d, thank you in advance and look forward for your reply!

**Comment by zkf1997** [comment]
> Thank you！ I ran this code on the remote server without displayer. But I indeed use the `osmesa ` mode. I am not farmilar with open3d, thank you in advance and look forward for your reply!

Using osmesa sometimes still can not solve the problem, it's related to the backend graphics interface. One easy solution is to run using a machine with a display. Another option is to remove the visualization code and the synthesis code can run on headless servers. After exporting the results files, you can run some other scripts for visualization.

**Comment by wang-zm18** [comment]
Thank you, I will have a try!
