### ISSUE TITLE
PROX-S vs. PROX

### ISSUE THREAD

**Issue by nicolasugrinovic** [zkf1997/COINS#2]
Hi, 
Amazing work! 

One quick question: 
- PROX is **100k** frames and PROX-S is **32k**. How did you pick the frames for this dataset? Did you downsample the sequences or picked keyframes by some criteria?

Thanks

**Comment by zkf1997** [comment]
The original PROX frames do not all have high-quality body fittings (e.g., with weird poses, obvious penetration with scenes). We use body fitting results of 41 sequences from[ LEMO](https://sanweiliti.github.io/LEMO/LEMO.html) for interaction annotation and only reserve the frames with annotated interaction labels. So PROX-S only covers a subset of PROX frames. 
We do not downsample the sequences in the provided data files.

**Comment by nicolasugrinovic** [comment]
I see, thank you for the response!.

To make it clear, when you say _clips without interaction_ what does this mean, idle states only, e.g., looking around without walking?  As I understand, walking is considered an interaction here, right?

**Comment by zkf1997** [comment]
I mean the frames without _labeled_ interactions. Current interaction annotation is not exhaustive and does not cover all the frames.  Dynamic and complex interactions such as counting numbers with fingers, push-ups on the table, are not annotated.

**Comment by nicolasugrinovic** [comment]
Great, thank you for the clarification.
