### ISSUE TITLE
About calculate global trans

### ISSUE THREAD

**Issue by Yamato-01** [zkf1997/COINS#5]
Good work! I have read the paper and found it wonderful! But there is a question about global trans. I'm confused about the calculating of global trans. Did the network calculating the global trans through the kinematic chain after regressing the global rotation and local joints rotation or only after regressing the global rotation? If former, it is rational, and I think the translation of SMPL is included in the output of Transformer Encoder. If latter, did you mean the 3,6,9th joints' rotation of SMPL remain unchanged?

**Comment by zkf1997** [comment]
Thanks for your question. From my understanding, you are talking about how to get the global translation using the generative models PelvisNet and BodyNet. So we first ignore the optimization-based refinement in the following discussion.
The global translation is determined in the first stage using PelvisNet. And in the second stage, BodyNet does not need to predict global translation. The output of PelvisNet is the global location and orientation of the body's pelvis joint, which defines a local pelvis coordinates frame. In the second stage, the output of transformer layers are locations in this local pelvis coordinates frame. The SMPL-X regressor does not predict the translation, but it just calculates the translation that can move the body pelvis to the location predicted by PelvisNet.
