### ISSUE TITLE
data creation and transformation

### ISSUE THREAD

**Issue by briqr** [zkf1997/COINS#6]
Dear authors,

Can you share or pinpoint the the code that creates data/train.pkl and data/test.pkl? Specifically, I would like to ask about the transformation that you used to transform from the original PROX-E SMPLX annotations to your annotations in these files.

Thanks

**Comment by zkf1997** [comment]
If you mean how to get the smplx body fittings, we use the results from https://sanweiliti.github.io/LEMO/LEMO.html.
