### ISSUE TITLE
about the global orient and transl

### ISSUE THREAD

**Issue by xuqingyao** [zkf1997/COINS#8]
hello, I find that the 'global_orient' and 'transl' in your train.kpl/test.pkl is different from those in LEMO dataset. My understanding is that the 'global_orient' and 'transl' provided by LEMO is in the camera coordinate system, and the camera extrinsic need to be provided to convert to the world coordinate system, but you directly provided the transformation matrix in the world coordinate system, right? If possible, can you provide the code for calculating your 'global_orient' and 'transl' from the original LEMO data? Thank you very much!

**Comment by zkf1997** [comment]
Hi, if you mean the transformation from camera to scene coordinates, please refer to the download page of [PROX](https://prox.is.tue.mpg.de/), and find Camera-to-World Transformations
